import AI_ToolsDetail from "../componets/Ai-ToolsDetail/Ai-ToolsDetail";

export const metadata = {
    title: "AI-ToolsDetail",
    description: "Generated by create next app",
  };
export default function AI_ToolsDetailPage() {
    return (
       <AI_ToolsDetail/>
    );
}