import AI_Tools from "../componets/Ai-Tools/Ai-Tools";

export const metadata = {
    title: "AI-Tools",
    description: "Generated by create next app",
  };
export default function AIToolsPage() {
    return (
        <>
        <AI_Tools/>
        </>
    );
}