import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./store/provider";
import HeaderPage from "./componets/Header/page";
import BoxPage from "./componets/Box/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <HeaderPage></HeaderPage>
          <BoxPage></BoxPage>
          {children}
          </Providers>
      </body>
    </html>
  );
}
